### ISSUE TITLE
Tienes el repositorio con visibilidad pública

### ISSUE THREAD

**Issue by ayhon** [puentemonte/SimuladorFisico#1]
Hola buenas. Soy un alumno de 2º en la FDI. Estabamos viendo hoy en IS2 GitHub y un amigo y yo nos hemos dado cuenta de que tenías el repositorio de IS2 como público. Además, tras entrar en tu perfil, hemos visto que tenías otro repositorio (Supongo que para la práctica de TP2, por el título)

Perdón por el cotilleo, pero bueno, pensé que te lo dejaría caer en un issue, supongo que te llegará un mensaje al correo. Te dejo este link, espero que te sea útil
[https://docs.github.com/en/enterprise-server@2.21/github/administering-a-repository/setting-repository-visibility](https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=&cad=rja&uact=8&ved=2ahUKEwjtvP_5xofvAhULyoUKHfudAdoQ3ywwAHoECAIQAg&url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DdQw4w9WgXcQ&usg=AOvVaw0aHtehaphMhOCAkCydRLZU)

Venga un saludo!

**Comment by puentemonte** [comment]
¡Muchas gracias por avisar y por la canción! Aunque creo que el link que me has pasado no era el correcto, he encontrado este otro: [https://docs.github.com/es/github/creating-cloning-and-archiving-repositories/about-repository-visibility#about-repository-visibility](https://www.youtube.com/watch?v=CID-sYQNCew)
